### PR TITLE
Add locking for update menus

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
testing on a large install would be welcome
passed smoke test and basic functional test

**Comment by holta** [comment]
> testing on a large install would be welcome

@neomatrixcode can you possibly help?

**Comment by tim-moody** [comment]
passed smoke test and simple function with latest changes

**Comment by holta** [comment]
> @neomatrixcode can you possibly help?

This PR is likely superseded by a better one here:

- PR #545

**Comment by neomatrixcode** [comment]
`sudo iiab-diagnostics` results after running the command `curl iiab.io/fast.txt | bash -s 544`

http://sprunge.us/FMib3p

**Comment by holta** [comment]
> http://sprunge.us/FMib3p?en

Many thanks @neomatrixcode for having tested:

- LARGE-sized as @tim-moody suggested
- 169G you installed
- about 35 Content Packs you installed

Conclusion: all testing helps!  But we still don't quite know what conditions bring about the iiab/iiab#3487 and iiab/iiab#3602 issues.

**Comment by tim-moody** [comment]
@neomatrixcode thanks for the big test.

I'm not seeing any errors in the diagnostics. Were any problems noticed? Does the home page look right? Is there a maps link?

**Comment by tim-moody** [comment]
Is there a reason not to merge this PR?

**Comment by holta** [comment]
> Is there a reason not to merge this PR?

Feel free and/or to merge PR #545 including this one.

**Comment by tim-moody** [comment]
Problems not addressed by the PR:

- Services are either not added (OSM) or only added as EN (kalite)
- Credits is only recognized as last menu item in EN

**Pull request merged**
