### PR TITLE
Download if filename is changed [OSM maps]

### PR DESCRIPTION
**Pull request by georgejhunt**
smoke tested and functionally tested for filename match and mismatch.

### CODE REVIEW

**Comment by tim-moody** [comment]
I don't understand what problem this solves. Do we have duplicate catalog entries that refer to different map regions?

**Comment by georgejhunt** [comment]
../assets/vector_maps-idx.json:
"en-osm-omt_central_america": {
    "menu_item": "en-osm-omt_central_america",
    "language": "en",
    "file_name": "en-osm-omt_central_america_2017-07-03_v0.22",
    "region": "central_america",
    "date": "2017-07-03",
    "size": "3953840128"
  },
maybe I stored the wrong thing in vector-map-idx.json as the key. Maybe what I put in file_name should actually be the key.

**Comment by tim-moody** [comment]
how about just introducing a unique map_id as a field to avoid confusion rather computing it
if map_id x has been downloaded there is no reason to get it again

**Comment by georgejhunt** [comment]
Since the filename has to be unique, it performs the function of a map_id.

The question  I am trying answer: Is there a version of this perma-ref
available in the catalog that is different from the one we have already. If
so, do not skip the download.

**Comment by tim-moody** [comment]
My understanding of the current logic is that a download that has been selected is only skipped if the map_id has already been downloaded. I think what you are proposing reduces to this logic.

**Comment by tim-moody** [comment]
the question of removing an earlier version (one with the same perm ref) is not handled, nor is it for any other type of content.

**Comment by tim-moody** [comment]
I think you are forcing an upgrade the user didn't ask for.

**Comment by georgejhunt** [comment]
I think I have a design flaw in my thinking. I agree that we don't want to
upgrade automatically, but on the other hand, we'd like to permit upgrade,
if a new map is available.

I had been thinking that I would just let a new map, displace an
older version in the catalog. But from the user's perspective, the new one,
and the old one, share the same perma_ref, and menu item. You had suggested
that the kiwix catalog is just additive. But, for maps, the newest is
always wanted, and it does not make sense to make the checkbox page long
with older maps that will never be chosen.

So an installed map needs to show up on the page of check boxes, along with
the newly available map. This is related to the green/blue colorizing
mentioned in one of our calls.

This needs more talk tomorrow

**Comment by holta** [comment]
Does this PR stand to be included in [IIAB 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes) in time, i.e. in QA'd and finalized in the coming 7-10 days?

**Comment by tim-moody** [comment]
Hope so

**Comment by holta** [comment]
@tim-moody 

I've just talked this over with @georgejhunt and he thinks we should go ahead and merge this now, as it's well-tested and necessary, can you do that?

**Comment by tim-moody** [comment]
I thought we discussed this on the last call and decided not to do it. I think the logic is flawed. Please show me a screen shot before and after this change.

**Comment by holta** [comment]
> I thought we discussed this on the last call and decided not to do it. I think the logic is flawed. Please show me a screen shot before and after this change.

@georgejhunt can you address this before to our Thur 2019-06-20 call if possible?

**Comment by tim-moody** [comment]
or just tell me: are there any installed regions that will appear on the selection screen that will be skipped or not skipped by this logic that are the opposite under the current logic.

**Comment by georgejhunt** [comment]
Cut and paste from a VM which has one map installed (the most recent one I think).
{
  "en-osm-omt_central_america": {
    "menu_item": "en-osm-omt_central_america", 
    "language": "en", 
    "file_name": "en-osm-omt_central_america_2017-07-03_v0.23", 
    "region": "central_america", 
    "date": "2017-07-03", 
    "size": "3953840128"
  }
}

This PR involves the following changes to make the vector-maps-idx.json global and persistent:
1. added line 30 ro admin-console.js var mapIdx = {}; // data about the installed maps 
2. changed in console/js/map_functions.js   to  line 50 	mapIdx = data;

Changes to ckecked callback in admin-console.js:
          var skipMap = false;
          if (mapInstalled.indexOf(map_id) >= 0){ <skip if the region is not known>
            // Does installed map have same basename (ignores .zip)
            var basename = mapCatalog[map_id].url.replace(/.*\//, ''); <get the url of this region from map catalog>
            // Clip off .zip
            basename = basename.replace(/\.zip/, '');
           < does the base name in the potentially new mapCatalog correspond with an installed filename? reference to the key in the vector-maps.idx.json above <"en-osm-omt_central_america": {>
            if (basename.indexOf(mapIdx['en-osm-omt_' + map_id].file_name) >= 0) skipMap = true;
< if the index is 0 or positive there is an exact match with installed file name and the mapCatalog -- so skip>
          }; 
          if (map_id in mapWip ||  skipMap) 
               consoleLog("Skipping installed Module " + map_id);
            else < otherwise install>
               instMapItem(map_id);

** Re-Testing**
1. pull the "one-or-more" branch which is this PR #211 
2. run ./install
3. In admin console, try to download the map which is already installed (fails to install with an alert suggesting that the install will occur, but then looking at utilities, display job status shows no download job)
4. Change the name in ../common/assets/vector-maps-idx.json so that the file name installed will not match with the catalog.
5 reboot-- because I want the new global idx to be picked up.
6. Try to do the map download again.
7. The scheduled job is visible in job queue.

**Comment by tim-moody** [comment]
My issue is not that I doubt that this PR will do what you say, only that so will the current code. Remove step 1 from your 6 steps and I believe you will get the same result, without all the extra logic.

**Comment by georgejhunt** [comment]
I want to be able to issue a changed map for central_america, download a
new mapCatalog via a button that we don't yet have, and have the check box
for central_america initiate a new download. My experience is that without
#1 above, the logic gives up and fails to download if there is already a
central_america map installed.

**Comment by tim-moody** [comment]
That is not my experience as long as the new map has a new file name, which I think you have said is effectively map_id.

**Comment by tim-moody** [comment]
I can not perform your test on the current code because I can't change regions.json at source, so let me propose a thought experiment:

download central america
pretend that the current region.json is the new version by renaming the downloaded central america to something else (with properly formatted name)
now download central america with admin console. I believe this will work.
If you now try to download it again without renaming it will not work, as expected.

**Comment by georgejhunt** [comment]
On Fri, Jun 21, 2019 at 7:37 AM Tim Moody <notifications@github.com> wrote:

> That is not my experience as long as the new map has a new file name,
> which I think you have said is effectively map_id.
>
Now I think we have gotten to the bottom of our talking past one another.
Map_id, as it is currently in my code, is the region "central_america". I
did not understand your question months ago, when you asked whether the
filenames of upgraded maps could be relied upon to be different. You were
asking whether your could rely upon map_id returned by the name value of
the checked checkbox, to have changed, when an upgraded map was released. I
thought you were asking whether the url would have changed, which seemed
obvious, because otherwise I could not download something different.

Whether at this point I can replace the name value of checkbox with the
basename of the url, i'm not sure. Probably some other code will break.
It'll take a little time to check out.

**Comment by georgejhunt** [comment]
No I think there will be no side affects if I change the value of the name
in the checkbox to basename of url. And it will fix the problem as you have
been saying.

**Comment by georgejhunt** [comment]
But /library/www/html/common/assets/vector-maps-idx.json is written with
the wrong key, for all of our installed base. The look up value in that
json file should be the basename of the url (minus the zip) and not the
region.

I don't have any kiwix or zims installed on any of my machines, so I cannot
easily verify this.

**Comment by georgejhunt** [comment]
A one line fix is in process, in testing, and probably ready tomorrow.
Thanks for helping resolve this.

**Comment by holta** [comment]
@georgejhunt has created https://github.com/iiab/iiab-admin-console/pull/224 instead.

**Pull request closed without merging**
