### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by georgejhunt**
Merging this PR needs to be simultaneous with PR into IIAB.
I favor setting a tag to v6.2.1 in both repos before merging this PR

### CODE REVIEW

**Comment by tim-moody** [comment]
I scanned these changes and didn't see anything that ought to be a problem

**Comment by tim-moody** [comment]
please tag iiab-admin-console as 0.2

**Comment by georgejhunt** [comment]
I'm not clear whether the tag you requested should be placed before or
after the PR is merged.

**Comment by tim-moody** [comment]
Above you said you were planning to tag prior to the merge. My comments were as to what the tag should be.

**Comment by georgejhunt** [comment]
Thanks

**Pull request merged**
