### PR TITLE
set system time from browser time

### PR DESCRIPTION
**Pull request by tim-moody**
if mobile device or win64 or macintel
and if apache sudo and turned on in menu

### CODE REVIEW

**Comment by holta** [comment]
Extremely promising.  Thanks @tim-moody and everyone who can test this:

> We have struggled with adding hardware RTC chips that have added cost and been unreliable. So I have a new feature in test whereby under certain conditions, the menuing system will update the system clock with the time from the browser of a device trusted to have the right time. It works as follows:
>
> 1. the apache_allow_sudo flag must be true (set with local vars) and the menu config must have allow_server_time_update true (set through the admin console)
>
> 2. if a device is mobile, as determined by the detectMobile function or has win64 or macintel in its device string then call updateServerTime
>
> 3. updateServerTime calls a php script that checks to see if the time has been set with NTP and if so returns. It then checks to see if the UTC version of the system time is more than 2 minutes behind the browser's UTC time and if so it uses date to set the clock to the browser's UTC time and fake-hwclock to save it.
>
> You can help test it by installing this PR #204

**Comment by holta** [comment]
INSTRUCTIONS to test this:

1. Install IIAB (http://d.iiab.io) onto an RPi 3 or 3 B+
2. sudo su -
3. cd /opt/iiab/iiab-admin-console
4. git checkout -b tim-moody-clock master
5. git pull https://github.com/tim-moody/iiab-admin-console.git clock
6. ./install
7. Test it by connecting nearby phones/laptops to your IIAB's internal WiFi access point, and then browsing to http://box or http://box.lan or http://172.18.96.1.

@tim-moody do you anticipate possibly making this work for NUC's etc later?

**Comment by tim-moody** [comment]
> do you anticipate possibly making this work for NUC's etc later?

not really needed on a server with a hardware clock, but any OS that has date, fake-hwclock, and timedatectl should work as long as the status returned by timedatectl contains the word synchronized for the line concerning ntp synchronization. raspbian and ubuntu 18.04 both do.

for now it must be turned off in the admin console if not needed.

**Comment by holta** [comment]
To document optional disabling if this feature in FAQ.IIAB.IO, what should we write?

**Comment by holta** [comment]
> INSTRUCTIONS to test this:
> 
> 1. Install IIAB (http://d.iiab.io) onto an RPi 3 or 3 B+

6.7 @avni & all, steps 2-to-6 should no longer be necessary now that this is merged and part of IIAB 7.0 master pre-releases as of ~3 hours ago.

6.8 Disconnect Internet COMPLETELY from your RPi (IIAB) and turn it off of 10 MINUTES.  To force off ntp (network time protocol) and to force its clock to be 10 min behind.

6.9 Turn your RPi 3 B+ (IIAB) back on.

> 7. Test it by connecting nearby phones/laptops to your IIAB's internal WiFi access point, and then browsing to http://box or http://box.lan or http://172.18.96.1 — does the IIAB's clock change almost instantly, as seen [before and after] when you run Raspbian's `date` command?

7.1 @avni can you help test that iPhone and MacBooks if you have access to either?  If so, please write onto this tkt which client machine HW model(s) and which browser version(s) you tested, Thanks!

**Comment by avni** [comment]
For some reason, I didn't see myself tagged to this thread in May. 

Did the 10 minute turn-off test today. Some interesting results. 

Prior to shutting off: 
pi@box:~ $ date
Sun 07 Jul 2019 04:02:07 PM EDT

After restarting, prior to browsing: 
pi@box:~ $ date
Sun 07 Jul 2019 03:20:12 PM EDT

After browsing: 
pi@box:~ $ date
Sun 07 Jul 2019 04:32:18 PM EDT

**Comment by avni** [comment]
Did another 10 minute test with iOS. Same results: 

after turning on: pi@box:~ $ date
Sun 07 Jul 2019 04:32:58 PM EDT

after accessing via iPhone iOS Safari: 
pi@box:~ $ date
Sun 07 Jul 2019 05:25:23 PM EDT

**Pull request merged**
