### PR TITLE
change autoupdate menu to true along with poweroff and update time

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by holta** [comment]
`"allow_poweroff": true,` (enabled by this PR) drives many teachers absolutely nuts.

When students turn off the Internet-in-a-Box right in the middle of the lesson, causing chaos for everyone.

So we'll just have to monitor this dicey situation...

**Comment by holta** [comment]
Related:

- http://FAQ.IIAB.IO -> '25 Is a "Rapid Power Off" button possible for low-electricity environments?'
- [https://wiki.iiab.io/go/FAQ#Is_a_%22Rapid_Power_Off%22_button_possible_for_low-electricity_environments?](https://wiki.iiab.io/go/FAQ#Is_a_%22Rapid_Power_Off%22_button_possible_for_low-electricity_environments?)

**Comment by tim-moody** [comment]
>"allow_poweroff": true, (enabled by this PR) drives many teachers absolutely nuts.
When students turn off the Internet-in-a-Box right in the middle of the lesson, causing chaos for everyone.

maybe overly ambitious. can be put back if required.

**Comment by holta** [comment]
> maybe overly ambitious. can be put back if required.

Probably makes sense.

Also docs (like http://FAQ.IIAB.IO -> "25 Is a "Rapid Power Off" button possible for low-electricity environments?") could definitely be modernized here.

So everyone (less technical implementers especially) gain a much clearer understanding of their options here~

**Pull request merged**
