### PR TITLE
change to accommodate new structure to zim_version_idx

### PR DESCRIPTION
**Pull request by georgejhunt**
tested on top of unclean image - via ./cp-menus and navigating to home page in client browser

### CODE REVIEW

**Comment by tim-moody** [comment]
see comment on names in iiab#1344

**Comment by tim-moody** [comment]
small point, but can (typeof zimVersions[module.zim_name].zimFileName != 'undefined' ) actually happen without a programming error? if not we are masking a programming error, which makes it harder to catch. The other check for undefined is because a user can add a menu item for which we have no zim and that is outside of our control, at least for now.

**Comment by tim-moody** [comment]
It may make sense to make this backwards compatible, i.e. check for new structure and use old if not present.

**Comment by georgejhunt** [comment]
This function works in current admin console

**Pull request closed without merging**
