### PR TITLE
console stealing all admin

### PR DESCRIPTION
**Pull request by georgejhunt**
This addresses iiab #2448 -- moodle .../admin/ not working.

### CODE REVIEW

**Comment by holta** [comment]
> This addresses iiab #2448 -- moodle .../admin/ not working.

Wow does http://box.lan/moodle full work with this 1-character change ?!

Ref: iiab/iiab#2448

**Comment by georgejhunt** [comment]
There is a native nginx conf file in the repo which also seems to work.
Who put it there? Why is it not enabled?

**Comment by holta** [comment]
> There is a native nginx conf file in the repo which also seems to work. Who put it there?

No idea.

> Why is it not enabled?

Feel free to experiment with enabling it — towards removing the need for Apache altogether ?

**Comment by tim-moody** [comment]
this looks right. did anyone try it?

**Comment by tim-moody** [comment]
I just tested it. Adm cons still works with this change. can't say for moodle.

**Comment by georgejhunt** [comment]
I can say that the change fixed the moodle admin problem

**Comment by tim-moody** [comment]
pretty insidious. wp-admin still worked. had to be */admin/*.php to be affected.

**Comment by holta** [comment]
http://box.lan/moodle quickly tested on Ubuntu 20.04 and RaspiOS Lite: appears to work bin both cases!

**Pull request merged**
