### PR TITLE
PR to correct menu defs: en-blockly-games.json, fr-blockly-games.json, fr-haitifutur.json

### PR DESCRIPTION
**Pull request by KW4NP**

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody & @KW4NP please review and merge if possible, Thanks!

(I fixed a merge conflict as well as fr-haitifutur.json that had several problems)

**Comment by tim-moody** [comment]
look ok, but have they been tested?
be aware that all of the catalog fields are no longer used and are stripped out by menu editing in the Adm Console

**Comment by holta** [comment]
> look ok, but have they been tested?

@KW4NP plz confirm you've tested all 3, after my tweaks, Thanks!

> be aware that all of the catalog fields are no longer used and are stripped out by menu editing in the Adm Console

@tim-moody is the documentation at https://github.com/iiab/iiab/wiki/IIAB-Menuing#menu-item-definition-fields up-to-date in this regard?

**Comment by tim-moody** [comment]
yes

**Comment by KW4NP** [comment]
I have just now tested and there is one error in the fr-haitifutur file.  Not sure how you want to change that but it has been fixed in my fork.

**Comment by holta** [comment]
Your Part 2 PR is at #199, Thanks!

**Pull request merged**
