### PR TITLE
handle case where single router name for  2.4 and  5 GHz

### PR DESCRIPTION
**Pull request by tim-moody**
Connecting by ssid can get either 2.4 or 5 GHz, and the latter breaks hostapd.

### CODE REVIEW

**Comment by tim-moody** [comment]
@avni @holta please test:

Test cases:
- router uses same name for both frequencies, but only 2.4GHz can be selected
- on reboot connection remains on 2.4GHz
- router has space in name
- user mistypes password
- user then corrects password
- user clicks forget all all wifi connections  and starts over

**Comment by holta** [comment]
Looks very promising.  So far I haven't had time to test.

@tim-moody's background tests:

- #579

**Comment by holta** [comment]
@avni might have time to test on Saturday?!

**Comment by avni** [comment]
I will test this next week - traveling currently.

**Comment by avni** [comment]
@tim-moody for the first test case: 
> router uses same name for both frequencies, but only 2.4GHz can be selected

I'm not clear what you mean by 'only 2.4GHz can be selected'? How would I disable the 5GHz from being selected as part of this test?

**Comment by tim-moody** [comment]
@avni the test is to make sure that the app doesn't allow selection of 5GHz even if one is available.

**Comment by avni** [comment]
For https://github.com/iiab/iiab-admin-console/pull/581, I think I need help understanding how to test and simulate the situation described. I updated my router, disabled SON, have 2.4GHz and 5GHz bands enabled with the same SSID, but not sure what to do now. I still only see one SSID in the Wifi list: 

Screenshot 2024-08-28 at 1 29 40 PM

Happy to do a live session @tim-moody or @holta if one of you can help. 🙏

**Comment by tim-moody** [comment]
I think that's a pass
 If you saw the name twice it would be a fail.

A further test would be if you connect iiab to the router and the hotspot still works then you connected on 2.4.

If you reboot iiab and it reconnects to 2.4 and hotspot still works then I think we are there.

**Comment by avni** [comment]
> I think that's a pass
> If you saw the name twice it would be a fail.

I think I'm doing this wrong. I'm testing from a VM where IIAB is not installed on the host computer. The screenshot above is from my laptop (MacOS M1). I think I need to test from an RPi where I do have IIAB on the host machine. Does that sound right?

**Comment by tim-moody** [comment]
Yes

**Comment by avni** [comment]
Tested from an RPi and TLDR is it works successfully. 
1. Disabled SON, have 2.4GHz and 5GHz bands enabled with the same SSID
2. Connected IIAB to a router, and hotspot works. 
3. Rebooted RPi, it connected to the 2.4 and hotspot still works. 

🚀 🏁

**Pull request merged**
