### PR TITLE
wifi password length and character limits

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
handles immediate change of password, but not change via ansible

**Comment by avni** [comment]
Confirmed that there is now a check in place when password is <8 characters (screenshot #1). 

When the overlay goes away, the new non-saved password shows (screenshot #2). There's no indicator on if the password is saved or not if you are just looking at the page. Is it possible to make clear if you have unsaved data on the page so the user knows they have to click, "Save Configuration"? 

Screenshot 2024-08-23 at 12 28 07 AM

Screenshot 2024-08-23 at 12 28 17 AM

**Comment by holta** [comment]
> Confirmed that there is now a check in place when password is <8 characters (screenshot

Great News (I too have confirmed!)

> Is it possible to make clear if you have unsaved data on the page so the user knows they have to click, "Save Configuration"?

@tim-moody might know??

**Comment by avni** [comment]
> The user changes the wifi password and Admin Console applies this change directly. Admin Console should validate the password.

1. I edited /etc/iiab/local_vars.yml directly and put a password that's <8 characters, 'test12'
2. Then ran, 'cd /opt/iiab/iiab', and 'sudo ./iiab-configure'
3. Logged into Admin console, and I see the new password. (screenshot #1)
4. When I click, "Save Configuration", however, it seems to skip the password check (or doesn't save because the password has not changed) and allows the 7 character password. (screenshot #2) I think it would be good if the UI could catch that the password changed on the backend doesn't comply with the requirements. 

Screenshot 2024-08-23 at 12 44 16 AM

Screenshot 2024-08-23 at 12 44 52 AM

**Comment by holta** [comment]
> I edited /etc/iiab/local_vars.yml directly and put a password that's <8 characters

Indeed that approach remains dangerous :-)

For now, IIAB's underlying network role (Ansible playbook) does not currently enforce the 8-to-63 "printable character" constraint, as mentioned here:

- https://github.com/iiab/iiab-admin-console/issues/577#issuecomment-2283311236
- https://github.com/iiab/iiab-admin-console/issues/577#issuecomment-2306285247

**Pull request merged**
