### PR TITLE
Show list of upstream routers for  connection

### PR DESCRIPTION
**Pull request by tim-moody**
tested on rpi w2 with intermittent problem iiab/iiab#3750

### CODE REVIEW

**Comment by tim-moody** [comment]
tested on rpi W2

**Comment by holta** [comment]
@EMG70 any comments on this new functionality, if you have time to test it in the coming week?

**Comment by EMG70** [comment]
> @EMG70 any comments on this new functionality, if you have time to test it in the coming week?

Yes sure, I will test and update you.

**Comment by holta** [comment]
@EMG70 mentions:

> one can view channel ID,Signal bars and security as on screenshot.

> I however did not see the server reboot when i clicked "forget all wifi connections"

IMG-20240617-WA0000~2

**Comment by tim-moody** [comment]
good point. It no longer needs to reboot to Forget, so I should take that off the screen. I don't think it ever needs to reboot when first connected either. I now just restart hostapd.

**Comment by tim-moody** [comment]
Were you able to connect over 5GHz? I was not expecting that to work. The screen shot shows hostapd on channel 6 and a connection to a router on channel 108. Can you confirm that the hotspot is working?

**Pull request merged**
