### PR TITLE
add tailscale to admin console

### PR DESCRIPTION
**Pull request by tim-moody**
allow installation of tailscale from Admin Console

tested on ub 24.04.1 vm

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody if possible, also consider removed OpenVPN functionality from Admin Console?

**Comment by tim-moody** [comment]
actually I thought it was already gone

**Comment by tim-moody** [comment]
but I guess you see it if you actually install openvpn

**Comment by holta** [comment]
Ah, ok.

Has the "VPN Control" sub-screen below also gone away?

image

**Comment by tim-moody** [comment]
I think if you click the link with openvpn not installed it will tell you support vpn is not available.

One day the link will allow you to activate tailscale, but for now it just doesn't do anything.

**Pull request merged**
