### PR TITLE
Oneline fix

### PR DESCRIPTION
**Pull request by georgejhunt**
The one line was going to be map_functions.js L126 (change region to url). But nothing is ever as simple in the end as it seems at first.
Tested in debian8 VM. Refuses to download what is already installed. Refuses to download a url that is in mapWip. Will download a new version of a map, that has a new URL.

### CODE REVIEW

**Comment by holta** [comment]
> Tested in debian8 VM

Why Debian 8?
Do you mean Debian 9 or 10?

**Comment by georgejhunt** [comment]
debian9

**Comment by holta** [comment]
Does this replace #211 ?

**Comment by georgejhunt** [comment]
yes

**Comment by tim-moody** [comment]
> VM. Refuses to download what is already installed. Refuses to download a url that is in mapWip. Will download a new version of a map, that has a new URL

This is a complaint or the expected behavior?

**Comment by tim-moody** [comment]
`mapInstalled[installed]`

installed sounds like a boolean. item or Installed_region would be better

**Comment by tim-moody** [comment]
thanks

**Comment by holta** [comment]
Can this (PR #224) and PR #226 be merged as I'm now preparing for IIAB 7.0 Preview 2?

Or are if they're not yet ready, what else is needed?

**Comment by tim-moody** [comment]
still don't understand why this was so complicated. the new alert is good though.

**Pull request merged**
