### PR TITLE
Add Internet Archive service to menuing

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by holta** [comment]
Thanks @tim-moody 

What else is likely needed here (just testing?)

**Comment by tim-moody** [comment]
yes

**Comment by tim-moody** [comment]
@holta please put the extra html into extra description (no <p> required)

**Comment by holta** [comment]
> @holta please put the extra html into extra description (no
> 
> required)

I tried that and it did not appear in Desktop browsers, not sure why, so I reverted to extra_html which does work.

(Mentioned on #207, the fully-tested/complete PR)

**Comment by tim-moody** [comment]
@holta was extra desc checked in edit menu properties?

**Comment by tim-moody** [comment]
@holta maybe you can add the image

**Pull request merged**
