### PR TITLE
0.4.1.5 new public key authentication

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
passed smoke test on raspbian and ub20 on rpi4

**Comment by tim-moody** [comment]
### Raspbian Tests
- [ ] get server public key OK
- [ ] get server nonce OK
- [ ] handle cmdsrv shutdown
- [ ] handle uwsgi shutdown
- [ ] invalid user rejected
- [ ] invalid password rejected
- [ ] valid user and password accepted
- [ ] prevent replay attack
- [ ] change password, invalid password
- [ ] change password, valid password
- [ ] logout clears credentials on form and in authData
- [ ] on login get encrypted token from server and clear credentials (future)
- [ ] authorize with token (future)

**Comment by tim-moody** [comment]
### Ubuntu 20 on Rpi Tests
- [ ] get server public key OK
- [ ] get server nonce OK
- [ ] handle cmdsrv shutdown
- [ ] handle uwsgi shutdown
- [ ] invalid user rejected
- [ ] invalid password rejected
- [ ] valid user and password accepted
- [ ] prevent replay attack
- [ ] change password, invalid password
- [ ] change password, valid password
- [ ] logout clears credentials on form and in authData
- [ ] on login get encrypted token from server and clear credentials (future)
- [ ] authorize with token (future)

**Comment by jvonau** [comment]
Basic upgrade over master, login works and no longer recorded in pam's /var/log/auth.log. Perhaps [pwauth and authnz-external](https://github.com/iiab/iiab-admin-console/blob/master/roles/console/tasks/main.yml#L1-L9) could be removed?

**Comment by holta** [comment]
Just FWIW the new red button "Sign Out / Retry Signin" ( under http://box/admin > Control ) doesn't instantly/visually log you out of IIAB's Admin Console...as buttons / tabs are still visible and clickable to navigate around certain parts of Admin Console...which is hardly the end of the world (as you're effectively logged out it would appear, and this is definitely not a banking web site...in fact many banking sites had similar behaviors ~20 years ago and were still generally secure despite!)

(i.e. this is just a tiny UX observation...not at all a serious problem...visible while testing `curl d.iiab.io/install-test.txt | sudo bash` on Raspbian Lite on RPi 4...using MIN-sized + Kolibri + Nextcloud...almost exactly as @floydianslips has done on Ubuntu 20.04 on RPi 4.)

**Comment by tim-moody** [comment]
Well you can't actually do anything (try to refresh job status for example), but I was expecting the login form to remain. I had a trick for modals to remain on in js-menu, maybe that is applicable here.

**Comment by tim-moody** [comment]
https://stackoverflow.com/questions/16152073/prevent-bootstrap-modal-from-disappearing-when-clicking-outside-or-pressing-esca

**Pull request merged**
