### PR TITLE
Create menus for IIAB roles, kiwix, rachel, and add kiwix statistics

### PR DESCRIPTION
**Pull request by georgejhunt**
Testing:

1. start with a dec 23 image
2. git pull iiab
3. ./iiab-install --reinstall
4. Clean install of master on iiab and iiab-admin-console.
5. on iiab-admin-console, do a pull, and ./install
6. Verify function of admin console and home page.
7. Remove all menu.json entries except first ald last
8. pull map2menu branch from georgejhunt/iiab/ 
9. cp the local_med_vars.yml to /etc/iiab
10. iiab-install --reinstall (had to turn off cups, and samba because of errors -- also did apt-get update)
11. pull map2menus branch from georgejhunt/iiab-admin-conosole
12. ./install
13. Results: menu now has kalite,text_zim,mediawiki,elgg,lokole,nextcloud,wordpess,kolibri,moodle,sugarizer
14. Install 5 kiwix items (small total 180mb)
15. run iiab-update-menus in /usr/bin/
16. 5 menu items added -- 2 were missing logos phet, and archwiki
17. Install 4 oer2go items (less than 100Mb)
18. run iiab-update-menus
19. Only one of the 4 showed up on home page (still some bugs)

I have installed this on top of 0.3-devel as well as on top of master

### CODE REVIEW

**Comment by tim-moody** [comment]
the purpose of genRegex was to create a generic set of regex expressions that could be used by all substitutions. you have changed it to something done for each item.

I don't understand the key scanning part.

**Comment by georgejhunt** [comment]
1. zim_version_idx.json is a dictionary indexed by perma_ref.
   2. In js-menu.js, the menuItem value is not the same as the lookup value
   of zim_versions_idx.
   3. We discussed creating another json with the search item being
   menuItem value. But you rejected that.
   4. I do not want to parse menuItem (remove first 3 characters, and the
   suffix following the last '_') -- because this would break the strategy for
   dealing with collision on zim-vs-rachel, and the substitution of "_" for
   "." in stackexchange zims with embedded "."s.
   5. So the key search is to find the substitution values corresponding to
   menuItem, which is a lookup jitem in second level dictionary of
   zim_versions_idx

This is a snippet of zim_versions_idx.json (before I added the date you
requested)
"wikem_en_all": {
    "media_count": "1070",
    "menu_item": "en-wikem_en_all",
    "language": "en",
    "tags": "wikem;_ftindex",
    "file_name": "wikem_en_all_2018-10",
    "article_count": "3434",
    "size": "38.2K"
  },
  "tes": {
    "media_count": "0",
    "menu_item": "en-test_zim",
    "language": "0",
    "tags": "0",
    "file_name": "test",
    "article_count": "0",
    "size": "0.00"
  }

**Comment by georgejhunt** [comment]
Last night in bed, it struck me that you must be using zim_name from
menu-defs to index into zim_versions_idx. to get at the link target.
I made it too hard.

**Comment by tim-moody** [comment]
exactly

**Comment by holta** [comment]
I'm presuming this can be closed, as it's being replaced by PR iiab/iiab-admin-console#109 and successors?

**Pull request closed without merging**
