### PR TITLE
logic backwards

### PR DESCRIPTION
**Pull request by tim-moody**
thought this was committed

### CODE REVIEW

**Comment by holta** [comment]
Just FYI this (building on PR #296 etc) uses convenience variable `is_rpi` defined in https://github.com/iiab/iiab-admin-console/blob/master/roles/console/files/js/admin_console.js#L700-704 here:

```
  // set convenience variable
  if (ansibleFacts.ansible_local.local_facts.rpi_model != 'none')
    is_rpi = true;
  else
    is_rpi = false;
```

**Comment by tim-moody** [comment]
not quite right. there is such a convenience variable on both front end and back end. This is the backend.

**Comment by holta** [comment]
So the front end inherits from this back end presumably?

**Comment by tim-moody** [comment]
no. both are just convenience variables independently defined

**Comment by holta** [comment]
Ah I see.  Here it is https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L2624-L2627 :

```
    if ansible_facts['ansible_local']['local_facts']['rpi_model'] != 'none':
        is_rpi = True # convenience
    else:
        is_rpi = False
```

**Pull request merged**
