### PR TITLE
subjective changes to form

### PR DESCRIPTION
**Pull request by tim-moody**
depends on iiab/iiab#2361

### CODE REVIEW

**Comment by tim-moody** [comment]
```
root@box-pi-test-raspbian:~# cat scan.awk
$1 == "BSS" {
    MAC = $2
    wifi[MAC]["enc"] = "Open"
}
$1 == "SSID:" {
    wifi[MAC]["SSID"] = $2
}
$1 == "freq:" {
    wifi[MAC]["freq"] = $NF
}
$1 == "signal:" {
    wifi[MAC]["sig"] = $2 " " $3
}
$1 == "WPA:" {
    wifi[MAC]["enc"] = "WPA"
}
$1 == "WEP:" {
    wifi[MAC]["enc"] = "WEP"
}
END {
    printf "%s\t\t%s\t%s\t\t%s\n","SSID","Frequency","Signal","Encryption"

    for (w in wifi) {
        printf "%s\t\t%s\t\t%s\t%s\n",wifi[w]["SSID"],wifi[w]["freq"],wifi[w]["sig"],wifi[w]["enc"]
    }
}

iw wlan0 scan | awk -f scan.awk
```

**Comment by tim-moody** [comment]
but it takes 5 seconds or so

**Comment by tim-moody** [comment]
also works on U20

**Comment by tim-moody** [comment]
https://blogs.gnome.org/dcbw/2016/05/16/networkmanager-and-wifi-scans/

**Comment by tim-moody** [comment]
https://launchpad.net/wicd

**Comment by tim-moody** [comment]
BUT  nmcli device wifi list is sub-second on raspbian. Not installed oob by u20. had to install all of networkmanager. (reset wired and wireless network connections)

**Comment by tim-moody** [comment]
on reboot can not login

**Comment by tim-moody** [comment]
on raspbian iw dev wlan0 scan is still > 5 sec and nmcli device wifi list < 1 sec
on u20 iw dev wlan0 scan is still > 5 sec and nmcli device wifi list is too the first time < 1 sec after that

**Comment by jvonau** [comment]
With the 5 second delay present might want to have a look at trying:
Kick off the scan with: `wpa_cli -i wlan0 scan`
Display the results of the scan: `wpa_cli -i wlan0 scan_results`
Seems to return the results pretty quick for me but I suspect that the more APs are present close by the longer the scan takes to complete.

**Comment by tim-moody** [comment]
wow. the scan was sub-second on raspbian after fresh boot with 16 APs visible.

unfortunately, on ub20 I got
```
root@box-pi-test-ub20:~# wpa_cli -i wlan0 scan
Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

```

there's no /etc/wpa_supplicant/wpa_supplicant.conf because we are using netplan.
I copied this into /etc/wpa_supplicant/wpa_supplicant.conf directly from raspbian with no change

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

```

**Comment by tim-moody** [comment]
Will leave wifi dropdown for later.

**Pull request merged**
