### PR TITLE
add functionality when wifi_up_down false

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
passed smoke test and hostapd functionality. otherwise vars get stored correctly, but processing functionality needs more testing

**Comment by tim-moody** [comment]
pushing for wider testing

**Comment by holta** [comment]
@tim-moody can you explain what you mean by "add functionality when wifi_up_down false" just a bit more, to help us all understand better?

**Comment by tim-moody** [comment]
basically reintroduced what was lost with the hostapd password changes, namely, if wifi_up_down is false you have no dual wifi adapters, so you may want to use the builtin wifi as an AP or as a means of connecting to an external router. That functionality was added back in. newly added was the ability to change the wifi_up_down parameter under configigure Network Parameters.

**Pull request merged**
