### PR TITLE
change default map source to contabo

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
awaiting consensus

**Comment by holta** [comment]
This seems reasonable.

@georgejhunt @jvonau & All let us know if there are objections?

**Comment by georgejhunt** [comment]
Ok with me. I was wondering whether I should change the iiab test page (small world, and small satellite mbtiles) to use rclone, or just use the https:// url which includes the access key. I'm inclined to https, and only install rclone in the admin-console. I do think we should only get from one source.

I propose that we put the map-catalog.json on githubusercontent

**Comment by tim-moody** [comment]
>I propose that we put the map-catalog.json on githubusercontent

sounds right. where is it now? http://download.iiab.io/content/OSM/vector-tiles/map-catalog.json seems to be the old one.

**Comment by georgejhunt** [comment]
The map-catalog.json installed by iiab/master is currently drawn from timmoody.com

**Comment by tim-moody** [comment]
how does it get there and where is it edited/created?

**Comment by georgejhunt** [comment]
Line 13 of
https://github.com/iiab/iiab/blob/master/roles/osm-vector-maps/tasks/install.yml
with soft coding of map_catalog_url at osm-vector-maps/defaults/main.yml L
19

**Comment by jvonau** [comment]
> I propose that we put the map-catalog.json on githubusercontent

Please, then iiab can just grab from github
> how does it get there and where is it edited/created?

Think the how does the file get uploaded and the editing questions go away once hosted on github.

**Comment by jvonau** [comment]
while the door is open where should cities1000.sqlite be hosted?

**Comment by tim-moody** [comment]
>with soft coding of map_catalog_url at osm-vector-maps/defaults/main.yml L19

I was looking at vars/default vars which has a different value

>Think the how does the file get uploaded and the editing questions go away once hosted on github.

only the upload

**Comment by jvonau** [comment]
For some reason I can't just do a PR against maps but mocked up at https://github.com/jvonau/maps/pull/1/files

**Comment by jvonau** [comment]
PR at https://github.com/iiab/maps/pull/54

**Pull request merged**
