### PR TITLE
Trial 0.3

### PR DESCRIPTION
**Pull request by georgejhunt**
This is mostly a manual merge of my stuff with 0.3-devel, because a lot of my changes were waffling, and rebase requires remembering how I came down on each issue

### CODE REVIEW

**Comment by tim-moody** [comment]
what will happen if someone clicks on the cups menu item?

**Comment by tim-moody** [comment]
I thought that previously module['has_live_menudef'] was used to indicate a menu def had already been generated. You seem to use it indicate one should be generated. Under what conditions are menu defs generated and what not? When is an html file generated?

**Comment by tim-moody** [comment]
why does calibre-web run on its own port? I thought it is just a web app. Perhaps I'm mistaken.

**Comment by tim-moody** [comment]
menu def is en-calibreweb.json or en-calibre-web.json

**Comment by tim-moody** [comment]
I'm not sure I like embedding get oer2go catalog in update menus. It should already have been run.

**Comment by georgejhunt** [comment]
I'm in the middle of doing a clean install of 0.3-devel branches (both
iiab-admin-console and iiab). I had lost function of stuff that was
working. There was code in /usr/bin and /opt/admin/scripts which had not
been copied back into the repo.
If I can recover function in the next hour or so I'll try to address your
issues. Having some trouble keeping track of all the PR's, branches, repos.
The target is to have it all in iiab and iiab-admin-console shared repos in
an hour or so.

I was thinking of iiab-update-menus  in a manner similar to
iiab-make-kiwix-lib. The user can copy rachel in /modules, and do some
command line stuff to get menus therefor.

Regarding html, I thought that we had said that I would not attempt to do
html, but I would not change you code which puts an attempt to parse into
/local/"purgatory"

We'll need to check on calibreweb.

My intention was to check for non-existent menu-def, and make a crack at it
if it does not exist.

**Comment by georgejhunt** [comment]
1. I did a clean from scratch of the 0.3-devel branches.
   2. Then installed 5 kiwix modules, and 5 rachel modules from the admin
   console.
   3. After the admin console indicated success, the home menu had not been
   updated.
   4. I ran iiab-update-menus, and the kiwix functions all showed up.
   5.  Rachel modules still missing
   6. Ran /opt/admin/cmdsrv/scripts/get_oer2go
   7. Three of the 5 downloaded modules appeared in home
   8. Bugs:
   1. en-wikipedia_en_all_novid menu-def is not found
      2. confusion about phet-english --- menu shows up and works, but a
      second also leads to same page -- but no logo
      3. Five menu items have no logo
   9. Changed /etc/iiab/local_vars.yml to install wikimedia, and did
   ./runrole mediawiki
   10. Then ran iiab-admin-console/install
   11. Mediawiki added to home page

i am driving to LA tomorrow, and will not be in action until Sunday.

**Pull request merged**
