### PR TITLE
add wifi password rules

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
Does not handle SCO.

**Comment by tim-moody** [comment]
somehow the js got reformatted, but too hard to undue and we want it anyway.

**Comment by tim-moody** [comment]
This only handles Control Panel Change Internal Wi-Fi Access Point Password.

Not entry of the password for ansible.

**Comment by holta** [comment]
This PR appears to be replaced by:

- PR #580

**Comment by holta** [comment]
Should this PR be closed?  (Or is it still possibly useful?)

**Comment by avni** [comment]
> Does not handle SCO.

Perhaps not important, but curious, what is SCO?

**Pull request closed without merging**
