### PR TITLE
test for local storage

### PR DESCRIPTION
**Pull request by georgejhunt**
Permits android <8 to display the menu items in the dumb browser.

### CODE REVIEW

**Comment by tim-moody** [comment]
can you catch setLocalStore() as well.

**Comment by georgejhunt** [comment]
done

**Comment by tim-moody** [comment]
presumed tested and working

**Comment by georgejhunt** [comment]
No I tested the original PR in the context that was failing on Android
captiveportal.
But I didn't circle back to test the additions you requested on
setLocalStorage.
I forgot, and I'm sorry.

**Pull request merged**
