### PR TITLE
0.5.4.2 presets - run roles backend

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
* Adds RUN-ANSIBLE-ROLES cmdsrv command
* Runs all roles listed in adm_const.iiab_roles for which actual installed/enabled state is different from iiab vars install/enabled state

**Comment by georgejhunt** [comment]
Very impressive work. Thank you Tim. 

I think I worked through what it would take to add a role that gets updated by Admin Console. But it may be easier to trace once the PR is in the code base.

**Comment by tim-moody** [comment]
and once it works. still testing

**Comment by tim-moody** [comment]
oops. I typed Truee in local vars for my test

so smoke and functional tests passed on ub 20.04.1 vm

**Pull request merged**
