### PR TITLE
Feature - Select Menu Item Icon

### PR DESCRIPTION
**Pull request by floydianslips**

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody: I know you're traveling a lot this month, but do you have time to look at this before the end of April?

**Comment by tim-moody** [comment]
On Ubuntu 18.04.1 VM the select list is empty

**Comment by floydianslips** [comment]
I will look into it when I get a chance.

**Comment by floydianslips** [comment]
That should fix the issue. Just an error in syntax.

**Comment by holta** [comment]
> That should fix the issue. Just an error in syntax.

@nataren can you review this for Josh D?  As @tim-moody is quite busy at the moment.

**Comment by holta** [comment]
@tim-moody can you please review and/or merge this PR of Josh's now?

**Pull request merged**
